### ISSUE TITLE
402 Payment Required when trying to run npm install

### ISSUE THREAD

**Issue by sebasijan** [igorxut/vue-ckeditor5#22]
I am tryin to use CKEditor 5 in my vue project.

After running

`npm install --save @ckeditor5-vue`

or

`npm install --save @ckeditor/ckeditor5-vue @ckeditor/ckeditor5-build-classic`

I just get this message: 

> npm ERR! code E402
> npm ERR! 402 Payment Required: @ckeditor/ckeditor5-vue@latest
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\basijan\AppData\Roaming\npm-cache\_logs\2019-06-21T13_54_03_699Z-debug.log
> 

Where the logfile contains:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '--save',
1 verbose cli   '@ckeditor/ckeditor5-vue' ]
2 info using npm@6.4.1
3 info using node@v10.15.1
4 verbose npm-session 88477e454857d4f1
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 402 https://namehere.pkgs.visualstudio.com/_packaging/NPM_Packages/npm/registry/@ckeditor%2fckeditor5-vue 532ms
8 silly fetchPackageMetaData error for @ckeditor/ckeditor5-vue@latest 402 Payment Required: @ckeditor/ckeditor5-vue@latest
9 timing stage:rollbackFailedOptional Completed in 1ms
10 timing stage:runTopLevelLifecycles Completed in 1786ms
11 verbose stack Error: 402 Payment Required: @ckeditor/ckeditor5-vue@latest
11 verbose stack     at fetch.then.res (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\lib\fetchers\registry\fetch.js:42:19)
11 verbose stack     at tryCatcher (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
11 verbose stack     at Promise._settlePromiseFromHandler (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
11 verbose stack     at Promise._settlePromise (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
11 verbose stack     at Promise._settlePromise0 (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
11 verbose stack     at Promise._settlePromises (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
11 verbose stack     at Async._drainQueue (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:133:16)
11 verbose stack     at Async._drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
11 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
11 verbose stack     at runCallback (timers.js:705:18)
11 verbose stack     at tryOnImmediate (timers.js:676:5)
11 verbose stack     at processImmediate (timers.js:658:5)
12 verbose cwd c:\repos\Schneider\OperationalCrm\SchneiderFS\SchneiderFS.Application.WebApi
13 verbose Windows_NT 10.0.18362
14 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "@ckeditor/ckeditor5-vue"
15 verbose node v10.15.1
16 verbose npm  v6.4.1
17 error code E402
18 error 402 Payment Required: @ckeditor/ckeditor5-vue@latest
19 verbose exit [ 1, true ]

```

What does this mean? Do I need to buy something before I can use this? If so, where do I buy it, and how does CKEditor know that I haven't paid for a subscription?

Thank you

**Comment by igorxut** [comment]
It is not my project. Look documentation: https://github.com/igorxut/vue-ckeditor5#nmp
